# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestor_ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_gestor(object):
    def setupUi(self, gestor):
        gestor.setObjectName("gestor")
        gestor.resize(367, 154)
        self.btn_vent2 = QtWidgets.QPushButton(gestor)
        self.btn_vent2.setIcon(QIcon('key.svg'))
        self.btn_vent2.setGeometry(QtCore.QRect(80, 50, 191, 22))
        self.btn_vent2.setObjectName("btn_vent2")

        self.retranslateUi(gestor)
        QtCore.QMetaObject.connectSlotsByName(gestor)

    def retranslateUi(self, gestor):
        _translate = QtCore.QCoreApplication.translate
        gestor.setWindowTitle(_translate("gestor", "Widget"))
        self.btn_vent2.setText(_translate("gestor", "Ventana 2"))
