# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venta_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana(object):
    def setupUi(self, ventana):
        ventana.setObjectName("ventana")
        ventana.resize(553, 492)
        self.tabWidget = QtWidgets.QTabWidget(ventana)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 501, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_tabul = QtWidgets.QPushButton(self.tab)
        self.btn_tabul.setGeometry(QtCore.QRect(100, 60, 251, 22))
        self.btn_tabul.setObjectName("btn_tabul")
        self.lbl_texto = QtWidgets.QLabel(self.tab)
        self.lbl_texto.setGeometry(QtCore.QRect(110, 140, 211, 31))
        self.lbl_texto.setText("")
        self.lbl_texto.setObjectName("lbl_texto")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(ventana)
        QtCore.QMetaObject.connectSlotsByName(ventana)

    def retranslateUi(self, ventana):
        _translate = QtCore.QCoreApplication.translate
        ventana.setWindowTitle(_translate("ventana", "Widget"))
        self.btn_tabul.setText(_translate("ventana", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ventana", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ventana", "Tab 2"))

